version: '3.8'
services: 
  gameapptestauto:
    image: jakefarm1775/jakegametest123:latest
    build: .
    container_name: gameapptestauto0101
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]
